### ISSUE TITLE
.co.za not supported?

### ISSUE THREAD

**Issue by evilsocket** [bobesa/go-domain-util#1]
As mentioned [here](https://github.com/evilsocket/xray/issues/8),  .co.za domains are not supported.

**Comment by bobesa** [comment]
I'll look into it 👍

**Comment by evilsocket** [comment]
Since we're here ... also `.uk` ( not `.co.uk`) is not handled, example: http://www.nhs.uk/

**Comment by bobesa** [comment]
Resolved by PR https://github.com/bobesa/go-domain-util/pull/2

**Comment by bobesa** [comment]
Use `go get -u github.com/bobesa/go-domain-util/domainutil` to update
